-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Client"
(
    id_client integer NOT NULL DEFAULT 'nextval('"Client_id_client_seq"'::regclass)',
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prenom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telephone numeric NOT NULL,
    mdps character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_naissance date,
    sex character varying(255) COLLATE pg_catalog."default",
    date_dinscription date,
    CONSTRAINT "Client_pkey" PRIMARY KEY (id_client),
    CONSTRAINT "U_client_email" UNIQUE (email),
    CONSTRAINT "U_client_telephone" UNIQUE (telephone)
);

CREATE TABLE IF NOT EXISTS public."Client vip"
(
    id_client_vip integer NOT NULL DEFAULT 'nextval('"Client vip_id_client_vip_seq"'::regclass)',
    id_client integer NOT NULL,
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prenom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telephone numeric NOT NULL,
    mdps character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_naissance date,
    sex character varying(255) COLLATE pg_catalog."default",
    date_dinscription date,
    CONSTRAINT "Client vip_pkey" PRIMARY KEY (id_client_vip)
);

CREATE TABLE IF NOT EXISTS public."Demande client"
(
    id_demande_client integer NOT NULL DEFAULT 'nextval('demande_client_id_demande_client_seq'::regclass)',
    id_client integer NOT NULL,
    "type bien" character varying COLLATE pg_catalog."default",
    "type de transaction" character varying COLLATE pg_catalog."default",
    "prix minimum" numeric,
    "prix maximum" numeric,
    "surface minimum" numeric,
    "nbr chambre minimum" character varying COLLATE pg_catalog."default",
    "date debut rechercher" date,
    "date fin recherche" date,
    "statut demande" character varying COLLATE pg_catalog."default",
    CONSTRAINT "Demande_client_pkey" PRIMARY KEY (id_demande_client)
);

CREATE TABLE IF NOT EXISTS public."Demande client valide"
(
    id_demande_client integer NOT NULL DEFAULT 'nextval('demande_client_id_demande_client_seq'::regclass)',
    id_client integer NOT NULL,
    "type bien" character varying COLLATE pg_catalog."default",
    "type de transaction" character varying COLLATE pg_catalog."default",
    "prix minimum" numeric,
    "prix maximum" numeric,
    "surface minimum" numeric,
    "nbr chambre minimum" character varying COLLATE pg_catalog."default",
    "date debut rechercher" date,
    "date fin recherche" date,
    "statut demande" character varying COLLATE pg_catalog."default",
    id_demande_client_valid integer NOT NULL DEFAULT 'nextval('"Demande client valide_id_demande_client_valid_seq"'::regclass)',
    CONSTRAINT "Demande client valide_pkey" PRIMARY KEY (id_demande_client_valid)
);

CREATE TABLE IF NOT EXISTS public."Demande client vip "
(
    id_demande_client integer NOT NULL DEFAULT 'nextval('demande_client_id_demande_client_seq'::regclass)',
    id_client integer NOT NULL,
    "type bien" character varying COLLATE pg_catalog."default",
    "type de transaction" character varying COLLATE pg_catalog."default",
    "prix minimum" numeric,
    "prix maximum" numeric,
    "surface minimum" numeric,
    "nbr chambre minimum" character varying COLLATE pg_catalog."default",
    "date debut rechercher" date,
    "date fin recherche" date,
    "statut demande" character varying COLLATE pg_catalog."default",
    id_demande_client_vip integer NOT NULL DEFAULT 'nextval('"Demande client vip _id_demande_client_vip_seq"'::regclass)',
    CONSTRAINT "Demande client vip _pkey" PRIMARY KEY (id_demande_client_vip)
);

CREATE TABLE IF NOT EXISTS public."Demande client vip valid "
(
    id_demande_client integer NOT NULL DEFAULT 'nextval('demande_client_id_demande_client_seq'::regclass)',
    id_client integer NOT NULL,
    "type bien" character varying COLLATE pg_catalog."default",
    "type de transaction" character varying COLLATE pg_catalog."default",
    "prix minimum" numeric,
    "prix maximum" numeric,
    "surface minimum" numeric,
    "nbr chambre minimum" character varying COLLATE pg_catalog."default",
    "date debut rechercher" date,
    "date fin recherche" date,
    "statut demande" character varying COLLATE pg_catalog."default",
    id_demande_client_vip integer NOT NULL DEFAULT 'nextval('"Demande client vip _id_demande_client_vip_seq"'::regclass)',
    id_demande_client_vip_valid integer NOT NULL DEFAULT 'nextval('"demande client vip valid _id_demande_client_vip_valid_seq"'::regclass)',
    CONSTRAINT "demande client vip valid _pkey" PRIMARY KEY (id_demande_client_vip_valid)
);

CREATE TABLE IF NOT EXISTS public."Proprietaire"
(
    id_proprietaire integer NOT NULL DEFAULT 'nextval('"Proprietaire_id_proprietaire_seq"'::regclass)',
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prenom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ville character varying(255) COLLATE pg_catalog."default",
    telephone numeric NOT NULL,
    mdps character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_naissance date,
    sex character varying(255) COLLATE pg_catalog."default",
    date_dinscription date,
    CONSTRAINT "Proprietaire_pkey" PRIMARY KEY (id_proprietaire),
    CONSTRAINT "U_Proprietaire_email" UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public."Proprietaire vip"
(
    id_proprietaire_vip integer NOT NULL DEFAULT 'nextval('"Proprietaire vip_id_proprietaire_vip_seq"'::regclass)',
    id_proprietaire integer NOT NULL,
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prenom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ville character varying(255) COLLATE pg_catalog."default",
    telephone numeric NOT NULL,
    mdps character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_naissance date,
    sex character varying(255) COLLATE pg_catalog."default",
    date_dinscription date,
    CONSTRAINT "Proprietaire vip_pkey" PRIMARY KEY (id_proprietaire_vip)
);

CREATE TABLE IF NOT EXISTS public."Rdv"
(
    id_rdv integer NOT NULL DEFAULT 'nextval('rdv_id_rdv_seq'::regclass)',
    id_demande_client_valid integer NOT NULL,
    date_rdv date NOT NULL,
    heure_rdv time without time zone,
    lieu_rdv character varying COLLATE pg_catalog."default",
    id_client integer NOT NULL DEFAULT 'nextval('"Rdv_id_client_seq"'::regclass)',
    id_proprietaire integer NOT NULL DEFAULT 'nextval('"Rdv_id_proprietaire_seq"'::regclass)',
    CONSTRAINT "RDV_pkey" PRIMARY KEY (id_rdv)
);

CREATE TABLE IF NOT EXISTS public."Rdv Vip "
(
    id_rdv integer NOT NULL DEFAULT 'nextval('rdv_id_rdv_seq'::regclass)',
    id_demande_client_valid integer NOT NULL,
    date_rdv date NOT NULL,
    heure_rdv time without time zone,
    lieu_rdv character varying COLLATE pg_catalog."default",
    id_client integer NOT NULL DEFAULT 'nextval('"Rdv_id_client_seq"'::regclass)',
    id_proprietaire integer NOT NULL DEFAULT 'nextval('"Rdv_id_proprietaire_seq"'::regclass)',
    id_rdv_vip integer NOT NULL DEFAULT 'nextval('"Rdv Vip _id_rdv_vip_seq"'::regclass)',
    CONSTRAINT "Rdv Vip _pkey" PRIMARY KEY (id_rdv_vip)
);

CREATE TABLE IF NOT EXISTS public.biens
(
    id_biens integer NOT NULL DEFAULT 'nextval('biens_id_biens_seq'::regclass)',
    description character varying(255) COLLATE pg_catalog."default",
    type_bien character varying(255) COLLATE pg_catalog."default",
    adresse character varying(255) COLLATE pg_catalog."default",
    ville character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(255)[] COLLATE pg_catalog."default",
    prix_estime numeric,
    etat character varying(255) COLLATE pg_catalog."default",
    id_proprietaire integer NOT NULL,
    CONSTRAINT biens_pkey PRIMARY KEY (id_biens)
);

CREATE TABLE IF NOT EXISTS public."biens loue"
(
    id_biens_loue integer NOT NULL DEFAULT 'nextval('"biens loue_id_biens_loue_seq"'::regclass)',
    id_biens integer NOT NULL,
    id_client integer NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    type_bien character varying(255) COLLATE pg_catalog."default",
    adresse character varying(255) COLLATE pg_catalog."default",
    ville character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(255)[] COLLATE pg_catalog."default",
    prix_estime numeric,
    etat character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "biens loue_pkey" PRIMARY KEY (id_biens_loue)
);

CREATE TABLE IF NOT EXISTS public."biens loue vip "
(
    id_biens_loue integer NOT NULL DEFAULT 'nextval('"biens loue_id_biens_loue_seq"'::regclass)',
    id_biens integer NOT NULL,
    id_client integer NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    type_bien character varying(255) COLLATE pg_catalog."default",
    adresse character varying(255) COLLATE pg_catalog."default",
    ville character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(255)[] COLLATE pg_catalog."default",
    prix_estime numeric,
    etat character varying(255) COLLATE pg_catalog."default",
    id_bien_loue_vip integer NOT NULL DEFAULT 'nextval('"biens loue vip _id_bien_loue_vip_seq"'::regclass)',
    CONSTRAINT "biens loue vip _pkey" PRIMARY KEY (id_bien_loue_vip)
);

CREATE TABLE IF NOT EXISTS public."biens vip"
(
    id_biens integer NOT NULL DEFAULT 'nextval('biens_id_biens_seq'::regclass)',
    description character varying(255) COLLATE pg_catalog."default",
    type_bien character varying(255) COLLATE pg_catalog."default",
    adresse character varying(255) COLLATE pg_catalog."default",
    ville character varying(255) COLLATE pg_catalog."default",
    code_postal character varying(255)[] COLLATE pg_catalog."default",
    prix_estime numeric,
    etat character varying(255) COLLATE pg_catalog."default",
    id_proprietaire integer NOT NULL,
    CONSTRAINT "biens vip_pkey" PRIMARY KEY (id_biens)
);

ALTER TABLE IF EXISTS public."Client vip"
    ADD CONSTRAINT "Client vip_id_client_fkey" FOREIGN KEY (id_client)
    REFERENCES public."Client" (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Demande client"
    ADD CONSTRAINT fk_demande_client FOREIGN KEY (id_client)
    REFERENCES public."Client" (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Demande client valide"
    ADD CONSTRAINT fk_demande_client_valid FOREIGN KEY (id_demande_client_valid)
    REFERENCES public."Demande client" (id_demande_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Demande client valide_pkey"
    ON public."Demande client valide"(id_demande_client_valid);


ALTER TABLE IF EXISTS public."Demande client valide"
    ADD CONSTRAINT fk_demande_client_valid_client FOREIGN KEY (id_client)
    REFERENCES public."Client" (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Demande client vip "
    ADD CONSTRAINT fk_demande_client_vip FOREIGN KEY (id_demande_client_vip)
    REFERENCES public."Demande client" (id_demande_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "Demande client vip _pkey"
    ON public."Demande client vip "(id_demande_client_vip);


ALTER TABLE IF EXISTS public."Demande client vip "
    ADD CONSTRAINT fk_demande_client_vip_client FOREIGN KEY (id_client)
    REFERENCES public."Client" (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Demande client vip valid "
    ADD CONSTRAINT fk_demande_client_vip FOREIGN KEY (id_demande_client)
    REFERENCES public."Demande client vip " (id_demande_client_vip) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Demande client vip valid "
    ADD CONSTRAINT fk_demande_client_vip_client FOREIGN KEY (id_client)
    REFERENCES public."Client vip" (id_client_vip) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."Proprietaire vip"
    ADD CONSTRAINT "Proprietaire vip_id_proprietaire_fkey" FOREIGN KEY (id_proprietaire)
    REFERENCES public."Proprietaire" (id_proprietaire) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."Rdv"
    ADD CONSTRAINT fk_rdv_client FOREIGN KEY (id_client)
    REFERENCES public."Client" (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rdv"
    ADD CONSTRAINT fk_rdv_p FOREIGN KEY (id_proprietaire)
    REFERENCES public."Proprietaire" (id_proprietaire) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rdv Vip "
    ADD CONSTRAINT fk_rdv_vip FOREIGN KEY (id_rdv)
    REFERENCES public."Rdv" (id_rdv) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rdv Vip "
    ADD CONSTRAINT fk_rdv_vip_client_vip FOREIGN KEY (id_client)
    REFERENCES public."Client vip" (id_client_vip) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Rdv Vip "
    ADD CONSTRAINT fk_rdv_vip_p FOREIGN KEY (id_proprietaire)
    REFERENCES public."Proprietaire vip" (id_proprietaire_vip) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.biens
    ADD CONSTRAINT biens_id_proprietaire_fkey FOREIGN KEY (id_proprietaire)
    REFERENCES public."Proprietaire" (id_proprietaire) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."biens loue"
    ADD CONSTRAINT "biens loue_id_biens_fkey" FOREIGN KEY (id_biens)
    REFERENCES public.biens (id_biens) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."biens loue"
    ADD CONSTRAINT "biens loue_id_client_fkey" FOREIGN KEY (id_client)
    REFERENCES public."Client" (id_client) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public."biens loue vip "
    ADD CONSTRAINT fk_bien_loue_bip FOREIGN KEY (id_biens_loue)
    REFERENCES public."biens loue" (id_biens_loue) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."biens vip"
    ADD CONSTRAINT "fk_bien_vip " FOREIGN KEY (id_biens)
    REFERENCES public.biens (id_biens) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "biens vip_pkey"
    ON public."biens vip"(id_biens);


ALTER TABLE IF EXISTS public."biens vip"
    ADD CONSTRAINT fk_bien_vip_ FOREIGN KEY (id_proprietaire)
    REFERENCES public."Proprietaire" (id_proprietaire) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;